# -*- coding: utf-8 -*-
"""Joint_Coordinates_Identification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wdiUZTzPeIJ5MsQmu5I3uyy1jkoPDNq6
"""

!pip install mediapipe
import cv2
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
import urllib.request
import os
import numpy as np

"""Download pose model"""

#We load pose estimation model from mediapipe tasks so that it exists locally before the pipeline starts.
# .task if the model file format used by the newer versions of mediapipe tasks. It contains: trained neural network weights + Model architecture + metadata/ configuration
MODEL_PATH = "pose_landmarker_heavy.task"
MODEL_URL  = (
    "https://storage.googleapis.com/mediapipe-models/"
    "pose_landmarker/pose_landmarker_heavy/float16/latest/"
    "pose_landmarker_heavy.task"
)
if not os.path.exists(MODEL_PATH):
    print("Downloading model...")
    urllib.request.urlretrieve(MODEL_URL, MODEL_PATH)
    print("Done.")

#Here we configure the basic properties of the video being processed
VIDEO_PATH  = "/content/drive/MyDrive/Dataset_Videos/Supine_Heel_Slides/Yash_1.mp4"  #Path of the video to be processed
SIDE       = "right"            #The side of joint coordinates that needs to be worked with

LANDMARK_INDICES = {
    "right": dict(shoulder=12, hip=24, knee=26, ankle=28, foot=32),
    "left":  dict(shoulder=11, hip=23, knee=25, ankle=27, foot=31),
}

#These are basic overlay characteristics for visibility on the video. Provides a visible skeleton overlay
SKELETON_COLOUR   = (0, 255, 0)     #green — full skeleton
KEY_JOINT_COLOUR  = (0, 0, 255)     #red   — your 5 key joints
ANGLE_COLOUR      = (255, 255, 0)   #yellow — angle text
DETECTED_COLOUR   = (0, 255, 0)     #green — status text
MISSING_COLOUR    = (0, 0, 255)     #red   — status text

#Angles are calculated using the three point formula. #Currently the dataframe contains raw joint coordinates, we need joint angles therefore we calculate them using trignometry
##Here we calculate the angle formed by three points, the angle is calculated at point B.
def calculate_angle(a, b, c):
    a, b, c = np.array(a), np.array(b), np.array(c) ##In the following step we get two vectors. Formula to get the angle - Cos theta = (ba.bc)/(|ba||bc|)
    ba = a - b
    bc = c - b
    denom = np.linalg.norm(ba) * np.linalg.norm(bc) + 1e-8
    cos_val = np.dot(ba, bc) / denom
    return float(np.degrees(np.arccos(np.clip(cos_val, -1.0, 1.0))))


def landmark_to_pixel(lm, w, h): #This function helps us convert the landmark coordinates provided by the pose estimation model into pixel coordinates so that the coordinates can be visualized
    return int(lm.x * w), int(lm.y * h) #The x coordinate is multiplied by width of the image and y coordinate is multiplied by the height of the image.

""" def draw_skeleton(frame, landmarks, w, h): #This function is used to draw the skeleton overlay. Input parameters: frame which is a numpy array containing the pixel values of the current frame. landmarks is the list of
#landmarks predicted by the pose estimation model, each landmark contains x, y and visibility. w is the width of the frame and h is the height of the frame.
#This code takes every body landmark detected by MediaPipe, copies its x, y, and z coordinates into a new MediaPipe-compatible landmark format (NormalizedLandmarkList), and stores all those converted landmarks together so MediaPipe’s drawing function can draw the pose skeleton.

    mp_pose = mp.solutions.pose #Import pose module. This accesses mediapipe pose definitions. Inside it: Pose landmark names, body connections, pose estimation utilities.
    #Example: mp_pose.POSE_CONNECTIONS returns connections like: shoulder -> Elbow, Elbow -> Wrist, etc.
    mp_drawing = mp.solutions.drawing_utils #Import drawing utilities. This module contains functions for drawing landmarks. It automatically draws landmarks and connections between landmarks instead of manually doing cv2.line() and cv2.circle() for all 33 landmarks.

    #Convert Tasks API landmarks to legacy format for drawing. Since the drawing utilities were built for the older Mediapipe Solutions API.
    landmark_proto = mp.framework.formats.landmark_pb2.NormalizedLandmarkList() #We create an empty object called landmark_proto. NormalizedLandmarkList is a structure that stores many landmarks together.
    #pb2 stands for protocol buffer version 2. Google uses this to store structured data. landmark_proto.landmark.extend() which is initially empty and .extend() adds multiple items into the list.
    #Example: nums = [1, 2], nums.extend([3, 4, 5]) therefore, nums = [1, 2, 3, 4, 5]
    landmark_proto.landmark.extend([
        mp.framework.formats.landmark_pb2.NormalizedLandmark(
            x=lm.x, y=lm.y, z=lm.z
        ) #one by one the landmarks are converted and stored into the object that was created.
        for lm in landmarks
    ])

    mp_drawing.draw_landmarks( #draw_landmarks is a built in mediapipe function that automatically draws circles for landmarks and lines between connected joints
        frame, #The frame on which the landmarks and connections are to be drawn
        landmark_proto, #The normalized coordinates of the landmarks. These coordinates are internally converted into pixel coordinates while drawing
        mp_pose.POSE_CONNECTIONS, #The pose connections that exists between the landmarks
        mp_drawing.DrawingSpec(color=SKELETON_COLOUR, thickness=2, circle_radius=3), #Landmark drawing style
        mp_drawing.DrawingSpec(color=SKELETON_COLOUR, thickness=2), #Connection drawing style
    )"""

def draw_skeleton(frame, landmarks, w, h):
    """Draw full MediaPipe pose skeleton manually — compatible with Tasks API."""

    # MediaPipe's 35 pose connections defined manually
    POSE_CONNECTIONS = [
        (0, 1), (1, 2), (2, 3), (3, 7),       # face left
        (0, 4), (4, 5), (5, 6), (6, 8),        # face right
        (9, 10),                                 # mouth
        (11, 12),                                # shoulders
        (11, 13), (13, 15),                      # left arm
        (12, 14), (14, 16),                      # right arm
        (15, 17), (15, 19), (17, 19),            # left hand
        (16, 18), (16, 20), (18, 20),            # right hand
        (11, 23), (12, 24),                      # torso sides
        (23, 24),                                # hips
        (23, 25), (25, 27), (27, 29), (27, 31), # left leg
        (24, 26), (26, 28), (28, 30), (28, 32), # right leg
        (29, 31), (30, 32),                      # feet
    ]

    # Draw all connections
    for start_idx, end_idx in POSE_CONNECTIONS:
        if start_idx < len(landmarks) and end_idx < len(landmarks):
            lm_start = landmarks[start_idx]
            lm_end   = landmarks[end_idx]

            # Only draw if both landmarks have reasonable visibility
            if lm_start.visibility > 0.3 and lm_end.visibility > 0.3:
                px_start = (int(lm_start.x * w), int(lm_start.y * h))
                px_end   = (int(lm_end.x * w),   int(lm_end.y * h))
                cv2.line(frame, px_start, px_end, SKELETON_COLOUR, 2)

    # Draw all landmark dots
    for lm in landmarks:
        if lm.visibility > 0.3:
            px = int(lm.x * w)
            py = int(lm.y * h)
            cv2.circle(frame, (px, py), 3, SKELETON_COLOUR, -1)

def draw_key_joints(frame, lms, indices, w, h): #Input is the current frame, the list of landmarks detected by mediapipe, indices tells us the landmarks which we actually want and the width and height of the frame.
    """Highlight the 5 key joints in red with labels."""
    joint_names = { #Give labels to each joint
        "shoulder": "SHO",
        "hip":      "HIP",
        "knee":     "KNEE",
        "ankle":    "ANK",
        "foot":     "FOOT",
    }
    coords = {}
    for joint, idx in indices.items(): #We loop through 5 joints
        px, py = landmark_to_pixel(lms[idx], w, h) #Conver the normalized coordinates to pixel coordinates for drawing
        coords[joint] = (px, py) #Store the coordinates in a dictionary.
        cv2.circle(frame, (px, py), 8, KEY_JOINT_COLOUR, -1) #This draws a filled circle on the landmark. cv2.circle(image, center, radius, color, thickness)
        cv2.putText(frame, joint_names[joint], (px + 10, py - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.55, KEY_JOINT_COLOUR, 2) #Set the label close to the circle drawn
    return coords

def draw_angles(frame, coords):
    """Calculate and display the 3 key angles next to their joints."""
    s  = coords["shoulder"]
    h  = coords["hip"]
    k  = coords["knee"]
    a  = coords["ankle"]
    f  = coords["foot"]

    knee_angle  = calculate_angle(h, k, a)
    hip_angle   = calculate_angle(s, h, k)
    ankle_angle = calculate_angle(k, a, f)

    #Draw angle values next to each joint. cv2.putText(image, text, position, font, size, color, thickness)
    cv2.putText(frame, f"Knee: {knee_angle:.1f}",
                (k[0] - 120, k[1]), #k is the knee coorindate - (640, 320) so this represents the position where the angle should be displayed. k[0] = 640, k[1] = 320
                cv2.FONT_HERSHEY_SIMPLEX, 0.65, ANGLE_COLOUR, 2)
    cv2.putText(frame, f"Hip: {hip_angle:.1f}",
                (h[0] - 120, h[1]),
                cv2.FONT_HERSHEY_SIMPLEX, 0.65, ANGLE_COLOUR, 2)
    cv2.putText(frame, f"Ankle: {ankle_angle:.1f}",
                (a[0] - 120, a[1]),
                cv2.FONT_HERSHEY_SIMPLEX, 0.65, ANGLE_COLOUR, 2)

    return knee_angle, hip_angle, ankle_angle

#Here the input arguments are the path of the video that needs to be visualized and the side which helps us focus on specific coordinates instead of all 33 joint coordinates
#Only a particular side of the 5 key joint angles is used
def run_visualiser(video_path, side="right"):
    from google.colab.patches import cv2_imshow # Added import here
    indices = LANDMARK_INDICES[side]

    base_options = python.BaseOptions(model_asset_path=MODEL_PATH)
    #Configure the loaded model and set parameters for inference
    options = vision.PoseLandmarkerOptions(
        base_options               = base_options, #The model is attached
        running_mode               = vision.RunningMode.VIDEO,   #Mediapipe Tasks supports multiple modes - image, video and live stream. Therefore, here we define the mode we want to operate in - which is the video mode.
        #During video processing (frame by frame processing), there is temporal tracking so the model keeps track of (or remembers) the previous frame
        num_poses                  = 1, #The main difference between this and solutions is that tasks can detect more than one people in the frame. Here, since we have set num_poses as 1 it will detect the person that gives the best confidence.
        min_pose_detection_confidence = 0.5, #Here, we define the minimum pose detection confidence, only detections with a confidence score equal to or above 0.5 will be considered, others will be ignored
        min_pose_presence_confidence  = 0.5, #This parameter checks that after the detection of a person, how confident is it that the pose landmarks (joint coordinates) are actually present and reliable enough to use
        min_tracking_confidence       = 0.5, #This parameter answers the question I knew where the body landmarks were in the previous frame. How confident am I that I can keep following (tracking) those same landmarks correctly in the current frame?
    ) #If we are processing a video fo 30fps running pose detection on every frame would be expensive so what mediapipe does is - it runs the full pose detection model on the first frame and then for the next frames it only tracks the joint coordinates since it has a context of the previous joint coordinates.
    """ Instead of asking every frame - where the person is. It already knows where the knee was in the last frame, it now checks where did it move now. What is actually happening here - Previous frame + motion estimate -> predict next landmark position.
    The tracker predicts then compares the prediction with the actual image features. If the prediction matches the image then the tracking confidence is high.
    In case the tracking confidence is too low, mediapipe will stop tracking and start detecting again from scratch from the same frame. """
    """ Mediapipe processes frames in the following manner:
    Stage 1 -> Detect a person
    Stage 2 -> Estimate body landmarks
    Stage 3 -> Track landmarks in the next frame

    The above three confidence parameters map to those stages:
    Stage 1 -> min_pose_detection_confidence
    Stage 2 -> min_pose_presence_confidence
    Stage 3 -> min_tracking_confidence
    min_pose_detection_confidence only helps detect a person, not if the joint coordinates can be detected accurately or not. It might be possible that a person might have a detection confidence of 0.8 but since a few joints are partially hidden
    min_pose_presence_confidence might be below the threshold of 0.5 and hence will be rejected. """


#Basic properties are extracted such as the frames one by one, the fps rate, the width and height of the image
    cap = cv2.VideoCapture(video_path)
    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    w   = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h   = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    print(f"\nVideo: {os.path.basename(video_path)}")
    print(f"Resolution: {w}x{h}  |  FPS: {fps}")
    print("\nControls:")
    print("  SPACE → pause / resume")
    print("  Q     → quit")
    print("  S     → save current frame as screenshot")
    print("  F     → slow motion (half speed)")
    print("  D     → fast forward (double speed)\n")

    #These variables control the video playback
    paused     = False #Keeps track of whether the video playback is paused or not. Initially the video is playing
    slow       = False #Tracks whether slow motion mode is active. False = normal playback speed
    fast       = False #Tracks whether fast forward mode is active. Initially fast forward mode is not active
    frame_idx  = 0 #Initially at frame 0
    delay      = int(1000 / fps) #1000/30 - 33 milli seconds. Therefore the next frame is shown after every 33 milli seconds

    with vision.PoseLandmarker.create_from_options(options) as detector:
        while cap.isOpened():
            if not paused: #proces the next frame only if the video is not paused
                ret, frame = cap.read() #Each frame is read
                if not ret: #If no frame is returned it means the video has ended so we break out of the loop
                    break

                #Run MediaPipe
                rgb      = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB) #Convert bgr to rgb. OpenCV stores images in bgr format but mediapipe requires rgb format
                mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb) #Create an image object that stores attributes of data and functions that operate on the data
                ts_ms    = int(frame_idx * 1000 / fps) #Time stamps are required for mediapipe, which are obtained by converting fps
                result   = detector.detect_for_video(mp_image, ts_ms) #The pose detection model is loaded her and provided an input of the image object and timestamp of the frame

                if result.pose_landmarks and len(result.pose_landmarks) > 0:
                    lms = result.pose_landmarks[0] #Store the landmarks of the first person (only person)

                    #Full skeleton
                    draw_skeleton(frame, lms, w, h)

                    #Key joints highlighted
                    coords = draw_key_joints(frame, lms, indices, w, h)

                    #Angle values
                    knee_angle, hip_angle, ankle_angle = draw_angles(frame, coords)

                    #Visibility scores for key joints
                    hip_vis   = lms[indices["hip"]].visibility
                    knee_vis  = lms[indices["knee"]].visibility
                    ankle_vis = lms[indices["ankle"]].visibility

                    #Displays detected status on the top left corner
                    cv2.putText(frame, "DETECTED", (20, 40),
                                cv2.FONT_HERSHEY_SIMPLEX, 1,
                                DETECTED_COLOUR, 2)

                    #Visibility scores bottom left
                    cv2.putText(frame,
                        f"Visibility — Hip:{hip_vis:.2f}  Knee:{knee_vis:.2f}  Ankle:{ankle_vis:.2f}",
                        (20, h - 20),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.55, (200, 200, 200), 1)

                    #If no person found
                else:
                    cv2.putText(frame, "NOT DETECTED", (20, 40),
                                cv2.FONT_HERSHEY_SIMPLEX, 1,
                                MISSING_COLOUR, 2)

                #Frame counter top right
                cv2.putText(frame, f"Frame: {frame_idx}",
                            (w - 180, 40),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (200, 200, 200), 2)

                frame_idx += 1

            cv2_imshow(frame) # Replaced cv2.imshow with cv2_imshow

            #Adjust playback speed. If normal speed then wait = delay, if video speed is slow then wait = delay * 2 and if video speed is fast then wait = delay / 2
            wait = delay * 2 if slow else (delay // 2 if fast else delay)
            key  = cv2.waitKey(wait) & 0xFF #Read keyboard input

            if key == ord('q'): #Stop
                break
            elif key == ord(' '):
                paused = not paused
            elif key == ord('s'):
                fname = f"screenshot_frame_{frame_idx}.jpg"
                cv2.imwrite(fname, frame)
                print(f"Screenshot saved → {fname}")
            elif key == ord('f'):
                slow = False
                fast = not fast
                print("Fast forward" if fast else "Normal speed")
            elif key == ord('d'):
                fast = False
                slow = not slow
                print("Slow motion" if slow else "Normal speed")

    cap.release()
    print("Done.")
#Run the main visualizer
run_visualiser(VIDEO_PATH, SIDE)