# -*- coding: utf-8 -*-
"""SHS_LSTM_Training_Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17nGvQ9PUi3cRXsSnWbpvByxT6djSwdgB
"""

from tensorflow import keras #keras is used to build and train neural networks
from sklearn.preprocessing import StandardScaler #used to scale all features to the same range
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

CSV_PATH= "/content/sample_data/features_shs.csv"
LABEL_CSV= "/content/sample_data/label_shs.csv"

"""STEP 1: LOAD AND READ THE DATASET

"""

def load_dataset(csv_path,label_csv):
  #read the csv and label_csv
  df= pd.read_csv(csv_path)
  label_df= pd.read_csv(label_csv)

  #to remove the frames for which rep_id is 0, that is, they dont belong to any rep
  #df["rep_id"] selects the rep_id column from the dataset
  #then it is seen if rep_id of each row is greater than 0 and produces a boolean list
  #when a boolean list is added in df[], pandas treats it as a filter and gives only those rows where the value is True
  df= df[df["rep_id"]>0]
  #list out what columns belong to the label
  label_columns= [
      "correct",
      "heel_lift",
      "velocity" #change depending on what are taken
  ]

  metadata_columns=[
      "video_id",
      "patient_id",
      "rep_id"
  ]

  drop_columns=[
      #add other features that are to be dropped
      "Hip_flexion_smooth",
      "Ankle_flexion_smooth",
      "Pelvic_lift_smooth",
      "Knee_flexion_jerk",
      "Hip_flexion_velocity",
      "Hip_flexion_accln",
      "Hip_flexion_jerk",
      "Ankle_flexion_velocity",
      "Ankle_flexion_accln",
      "Ankle_flexion_jerk",
      "Pelvic_lift_velocity",
      "Pelvic_lift_accln",
      "Pelvic_lift_jerk",
  ]

  #features
  x= df.drop(columns= drop_columns + metadata_columns) #since this csv no longer contains the labels
  metadata= df[metadata_columns]
  #labels
  y= label_df[label_columns]
  metadata_labels= label_df[metadata_columns]

  #validating the dataset
  #checking basic dataset information
  print(f"Shape of the dataset: {df.shape}") #.shape returns a tuple in the format (rows, columns)
  print(f"Number of Features: {x.shape[1]}") #shape[1] returns the number of columns
  print(f"Number of Labels: {y.shape[1]}")

  #print columns with missing values
  #isnull() makes a boolean table the same size as df, where True means value is missing
  #the first sum(), sums over all rows of a column. second sum() sums over all columns and runs the next block only if ANY value is missing
  if df.isnull().sum().sum() > 0:
    print(f"Columns with missing values: {df.isnull().sum()[df.isnull().sum()>0]}") #this prints only those columns where any value is missing

  #print columns with infinite values
  numeric_x= x.select_dtypes(include=[np.number])
  inf_cols= numeric_x.columns[np.isinf(numeric_x).any()]
  print(f"Columns with infinite values: {inf_cols}")

  #check the data types of the features
  print(f"Datatypes of all features: {x.dtypes}")

  #print how many reps in each category (label distribution)
  print(f"Label Distribution: {y.sum()}")

  #print the statistics of the features
  print(f"Statistics: {x.describe().T}")

  frames_per_rep= metadata.groupby(["video_id", "rep_id", "patient_id"]).size()
  print(f"Frames per rep: {frames_per_rep.describe()}")

  return x,y,metadata,metadata_labels,label_columns

x,y,metadata,metadata_labels,label_columns= load_dataset(CSV_PATH,LABEL_CSV)

"""STEP 2: SPLIT THE DATASET

"""

#splitting the dataset into training, testing and validation
#this split should be made patient wise. data of no other patient should be in two different sets to avoid data leakage
def split_dataset(x,y,metadata,metadata_labels):
  #to get a list of all patient names exactly once
  unique_patients= metadata["video_id"].unique()
  #split into train and temporary (test + val)
  train_patients, temp_patients= train_test_split(unique_patients, test_size= 0.3, random_state=42, shuffle=True)
  #random state= 42 keeps the split reproducible. every time this code is run, it gives the same split
  #split the temporary set into test and val
  test_patients, val_patients= train_test_split(temp_patients, test_size=0.5, random_state=42, shuffle=True)
  #this gives 70% training set, 15% test and 15% validation

  #to extract the corresponding rows into training set
  #first create boolean masks for train, test, val using patient_id, which will be passed through all rows to classify them to the corresponding sets
  #isin() returns True if the row belongs in the particular set. for every row, it checks if the patient belongs to train_patients/test_patients/val_patients
  #metadata["patient_id"] selects just that columns
  #the boolean mask is just a list of True or False, depending on whether that patient is in the set or not
  train_mask= metadata["video_id"].isin(train_patients) #this gives only those patient_ids which are there in train patients
  test_mask= metadata["video_id"].isin(test_patients)
  val_mask= metadata["video_id"].isin(val_patients)

  #make the final train, test, val feature and label set
  #pandas has a special feature called boolean indexing
  #since [train_mask] is not a column name, it gets that it is a Series of True and False with the same index as x
  #instead of a column name if a boolean Series is passed, pandas interprets it as- return only those rows where the mask is true
  x_train= x[train_mask] #pandas keeps those rows with True
  x_test= x[test_mask]
  x_val= x[val_mask]

  #the train mask created from frame level dataset- that of features cannot be directly applied to this rep level dataset of labels
  label_train_mask = metadata_labels["video_id"].isin(train_patients)
  label_test_mask = metadata_labels["video_id"].isin(test_patients)
  label_val_mask = metadata_labels["video_id"].isin(val_patients)
  y_train= y[label_train_mask]
  y_test= y[label_test_mask]
  y_val= y[label_val_mask]

  metadata_train= metadata[train_mask]
  metadata_test= metadata[test_mask]
  metadata_val= metadata[val_mask]

  metadata_labels_train= metadata_labels[label_train_mask]
  metadata_labels_test= metadata_labels[label_test_mask]
  metadata_labels_val= metadata_labels[label_val_mask]

  return(x_train, x_test, x_val, y_train, y_test, y_val, metadata_train, metadata_test, metadata_val, metadata_labels_train, metadata_labels_test, metadata_labels_val)

(x_train, x_test, x_val,
     y_train, y_test, y_val,
     metadata_train, metadata_test, metadata_val,
     metadata_labels_train, metadata_labels_test,
     metadata_labels_val) = split_dataset(x, y, metadata, metadata_labels)

"""STEP 3: ENCODE NON NUMERIC FEATURES

"""

def encode_features(x_train, x_test, x_val):
  #create the encoder. in case any unknown class is received at the time of deployment, ignore it
  encoder= OneHotEncoder(handle_unknown="ignore", sparse_output=False)
  #next, fit the encoder to only the columns that has categorical data
  #["phase"] gives a 1D series. [["phase"]] gives a 2D dataframe
  encoder.fit(x_train[["phase"]])
  #.fit() is a method that each class implements differently
  #with this OneHotEncoder object, .fit reads the entire column passed and learns the unique categories and stores them inside the encoder object
  #here, after fitting, the encoder object just stores the found categories

  #apply what the encoder learnt and transform the phase column
  #.transform changes the column into a numpy array of dimensions (nxm) where n is the number of rows and m is the number of categories
  #phase_train is not a dataframe anymore
  phase_train= encoder.transform(x_train[["phase"]])
  phase_test= encoder.transform(x_test[["phase"]])
  phase_val= encoder.transform(x_val[["phase"]])

  #now convert the numpy arrays back into dataframes
  #for this, first get the names of the encoded columns
  encoded_columns= encoder.get_feature_names_out(["phase"])
  #then convert the numpy array to dataframe
  phase_train= pd.DataFrame(phase_train, columns= encoded_columns, index= x_train.index)
  phase_test= pd.DataFrame(phase_test, columns= encoded_columns, index= x_test.index)
  phase_val= pd.DataFrame(phase_val, columns= encoded_columns, index= x_val.index)

  #merge both the dataframes. but first remove the original phase columns
  x_train= x_train.drop(columns=["phase"])
  x_test= x_test.drop(columns=["phase"])
  x_val= x_val.drop(columns=["phase"])

  #now merge (concatenate) the two dataframes
  x_train= pd.concat([x_train, phase_train], axis=1) #axis=1 stacks columns
  x_test= pd.concat([x_test, phase_test], axis=1)
  x_val= pd.concat([x_val, phase_val],axis=1)
  #return the processed datasets
  return x_train, x_test, x_val, encoder

"""STEP 4: SCALE THE FEATURES"""

def scale_features(x_train, x_test, x_val):
  #create the scaler object. it transforms each feature/column so that it has mean=0 and std dev=1
  #standardization is better in this case because it is less sensitive to new values outside the values of the training set
  scaler= StandardScaler()
  #the scaler object hasnt learnt anything yet
  #upon doing scaler.fit, the scaler object goes through each column independently
  #then for each column, it computes the mean and then the standard deviation. so after fitting the scaler object contains the mean and std dev of each column
  #scaler.fit only learns and stores the information
  #for this first take only the numerical columns
  numerical_columns= x_train.select_dtypes(include=[np.number]).columns
  #fit only on the training set and not on whole dataset. since fit learns and stores information, if whole dataset is used, the information from test and validation leaks into training data
  #also, the mean and std dev the training and testing dataset is scaled on, should be the same (from x train). if different mean and std dev used for test data then it may be scaled differently than trained
  #for example, if a value 100 is scaled to 0 in train (according to train mean and std dev), the same value could be scaled to 0.5 in test if mean and std dev of test is used separately
  #so, mean and std dev is taken from training set (fit only on the training set) and used to transform training, testing and validation set
  scaler.fit(x_train[numerical_columns])
  #transform the training set
  #.transform does scaled value= (value-mean)/std dev, for every value, taking the mean and std dev of that particular columns
  x_train[numerical_columns]= scaler.transform(x_train[numerical_columns])
  #transform the testing set
  x_test[numerical_columns]= scaler.transform(x_test[numerical_columns])
  #transform the validation set
  x_val[numerical_columns]= scaler.transform(x_val[numerical_columns])

  return x_train, x_test, x_val

"""STEP 5: CREATE SEQUENCES"""

def create_sequences(x_train, metadata_train):

  #to group all frames belonging to the same rep- they need to be grouped on the basis of video_id, patient_id, and rep_id
  #frames where all these are common- grouped together as one sequence- one training sample
  #groupby takes all rows that have the same values in these columns and groups them into one single group
  groups= metadata_train.groupby(["video_id", "rep_id"])
  #each group represents one rep_id in the dataset
  #groups is a pandas DataFrameGroupBy object

  #create a list to store the sequence from each rep_id
  x_sequences=[]
  #create a list to store the key that maps to each sequence
  sequence_keys=[]

  for (video_id, rep_id), group in groups:
    #to get both- the group's identifying values (video_id, patient_id, rep_id) and the rows belonging to that group
    #group.index contains the original row indices of the rows that belong to that particular group
    #(video_id, patient_id, rep_id) is the group key and tells which rep. "group" tells which rows in that group

    #get the indices of all the frames belonging to this rep_id
    group_indices= group.index

    #get feature values of all the frames in this rep
    rep_features= x_train.loc[group_indices]

    #this is a DataFrame now but LSTM expects a numpy array
    rep_features= rep_features.to_numpy()

    #append to the list.
    #x_sequences is a python list where x_sequences[0] corresponds to the numpy array containing all features/frames of rep 1
    x_sequences.append(rep_features)

    #the (video_id, patient_id, rep_id) key maps to which sequence needs to be preserved in order to attach the rep wise labels
    sequence_keys.append((video_id, rep_id))

  return x_sequences, sequence_keys

"""STEP 6: MATCH SEQUENCES AND LABELS

"""

def match_labels(x_sequences, sequence_keys, metadata_labels, y):
  #x_sequences are the actual input sequences
  #sequence_keys are (video_id, patient_id, rep_id) that belong to each sequence

  #create a label look up dictionary where the keys would be added using the metadata of the labels
  label_lookup={}

  #create an empty list to store only the label list in the exact order as of sequences
  y_sequences=[]

  #to add the keys to this look up dictionary, loop through the metadata labels column
  for idx, row in metadata_labels.iterrows():
    #where idx is the index of the rows and row is the (video_id, patient_id, rep_id) of the entire row
    #now construct the composite key
    key= (row["video_id"], row["rep_id"])
    #.loc[idx] takes the list of labels (correct, heel_lift, velocity) for that particular row
    #.to_numpy() then converts it to a numpy list
    label= y.loc[idx].to_numpy()
    #now put the key and label together
    label_lookup[key]= label
    #after the loop ends, label_lookup contains the label of every rep_id in the split

  #loop over the dictionary to extract only the values (labels) from the key value pair
  for key in sequence_keys:
    #till now, label lookup has the labels stored in the order of what is stored in label csv. in order to match the order of x_sequences
    label= label_lookup[key]
    y_sequences.append(label)
    #this matches the feature sequences and label sequences in the same order

  return x_sequences, y_sequences

"""STEP 7: CHECK CLASS DISTRIBUTION"""

def class_distribution(y_sequences, label_columns):
  y_train_array= np.array(y_sequences)
  #we have to count how many rep_ids are positive for each label
  positive_counts= y_train_array.sum(axis=0) #axis=0 sums over each column
  #make it into a dictionary that has the label name and count for reps for that label
  distribution= dict(zip(label_columns, positive_counts))

  return distribution

"""STEP 8: HANDLE CLASS IMBALANCE"""

# def handle_class_imbalance(y_sequences, label_columns):
#   distribution= class_distribution(y_sequences, label_columns)
#   #in order to assign weights, we also need the negative counts
#   for label, positive_counts in distribution.items():
#     negative_counts= len(y_sequences)- positive_counts

#   #we need both, the positive and negative weights
#   #TRY MULTIPLE WEIGHT BALANCING APPROACHES

def handle_class_imbalance(y_sequences, label_columns):
    y_array = np.array(y_sequences)
    total_reps = len(y_sequences)
    class_weights = {}

    for i, label in enumerate(label_columns):
        positive_count = y_array[:, i].sum()
        negative_count = total_reps - positive_count

        # avoid division by zero if a class has no positives
        if positive_count == 0:
            print(f"WARNING: {label} has no positive examples")
            class_weights[label] = {"positive": 1.0, "negative": 1.0}
            continue

        # inverse frequency weighting
        # higher weight for the minority class (positive examples)
        positive_weight = total_reps / (2 * positive_count)
        negative_weight = total_reps / (2 * negative_count)

        class_weights[label] = {
            "positive": positive_weight,
            "negative": negative_weight
        }

        print(f"{label}: positives={int(positive_count)}, "
              f"negatives={int(negative_count)}, "
              f"positive_weight={positive_weight:.3f}, "
              f"negative_weight={negative_weight:.3f}")

    return class_weights

def pad_sequences_custom(x_sequences, y_sequences):
    # find the longest rep in the dataset
    max_len = max(seq.shape[0] for seq in x_sequences)
    num_features = x_sequences[0].shape[1]
    num_labels = len(y_sequences[0])

    # create zero-padded arrays
    x_padded = np.zeros((len(x_sequences), max_len, num_features))
    y_array = np.array(y_sequences)  # shape: (num_reps, num_labels)

    # create mask to track which frames are real vs padded
    # 1 = real frame, 0 = padded frame
    mask = np.zeros((len(x_sequences), max_len))

    for i, seq in enumerate(x_sequences):
        seq_len = seq.shape[0]
        x_padded[i, :seq_len, :] = seq
        mask[i, :seq_len] = 1

    print(f"Padded shape: {x_padded.shape}")
    print(f"Labels shape: {y_array.shape}")
    print(f"Max sequence length: {max_len}")
    print(f"Num features: {num_features}")

    return x_padded, y_array, mask, max_len

def build_lstm_model(num_features, num_labels, max_len, hidden_size=64, dropout_rate=0.3, num_layers=1):
    # input layer
    inputs = keras.Input(shape=(max_len, num_features), name="input")

    # masking layer tells LSTM to ignore padded zero frames
    x = keras.layers.Masking(mask_value=0.0)(inputs)

    # LSTM layers
    # if num_layers > 1, intermediate layers need return_sequences=True
    for i in range(num_layers):
        return_seq = True if i < num_layers - 1 else False
        x = keras.layers.LSTM(
            hidden_size,
            return_sequences=return_seq,
            name=f"lstm_{i+1}"
        )(x)
        x = keras.layers.Dropout(dropout_rate, name=f"dropout_{i+1}")(x)

    # classification head
    # sigmoid because each label is independent binary decision
    outputs = keras.layers.Dense(
        num_labels,
        activation="sigmoid",
        name="classification_output"
    )(x)

    model = keras.Model(inputs=inputs, outputs=outputs)

    model.summary()
    return model

def build_weighted_loss(class_weights, label_columns, y_array):
    # build a weight tensor of shape (num_labels, 2)
    # index 0 = negative weight, index 1 = positive weight
    pos_weights = np.array([
        class_weights[label]["positive"] for label in label_columns
    ], dtype=np.float32)

    neg_weights = np.array([
        class_weights[label]["negative"] for label in label_columns
    ], dtype=np.float32)

    def weighted_binary_crossentropy(y_true, y_pred):
        import tensorflow as tf
        y_true = tf.cast(y_true, tf.float32)

        # per-sample per-label weight
        # where y_true=1 use positive weight, where y_true=0 use negative weight
        weights = y_true * pos_weights + (1 - y_true) * neg_weights

        # standard binary crossentropy per element
        bce = keras.backend.binary_crossentropy(y_true, y_pred)

        # apply weights
        weighted_bce = bce * weights

        return keras.backend.mean(weighted_bce)

    return weighted_binary_crossentropy

def compile_and_train(model, x_train_pad, y_train_arr,
                      x_val_pad, y_val_arr,
                      weighted_loss_fn,
                      epochs=100, batch_size=32):

    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=0.001),
        loss=weighted_loss_fn,
        metrics=[
            keras.metrics.BinaryAccuracy(name="accuracy"),
            keras.metrics.AUC(name="auc", multi_label=True)
        ]
    )

    # callbacks
    callbacks = [
        # save best model based on validation loss
        keras.callbacks.ModelCheckpoint(
            filepath="best_model.keras",
            monitor="val_loss",
            save_best_only=True,
            verbose=1
        ),
        # stop training when validation loss stops improving
        keras.callbacks.EarlyStopping(
            monitor="val_loss",
            patience=15,
            restore_best_weights=True,
            verbose=1
        ),
        # reduce learning rate when plateau
        keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss",
            factor=0.5,
            patience=7,
            min_lr=1e-6,
            verbose=1
        )
    ]

    history = model.fit(
        x_train_pad, y_train_arr,
        validation_data=(x_val_pad, y_val_arr),
        epochs=epochs,
        batch_size=batch_size,
        callbacks=callbacks,
        verbose=1
    )

    return model, history

def evaluate_model(model, x_test_pad, y_test_arr, label_columns):
    from sklearn.metrics import (
        classification_report,
        confusion_matrix,
        roc_auc_score,
        f1_score,
        precision_score,
        accuracy_score,
        recall_score
    )

    # get raw predictions between 0 and 1
    y_pred_prob = model.predict(x_test_pad)

    # convert to binary using 0.5 threshold
    y_pred_binary = (y_pred_prob >= 0.5).astype(int)

    print("\n" + "="*60)
    print("EVALUATION METRICS PER CLASS")
    print("="*60)

    for i, label in enumerate(label_columns):
        y_true_col = y_test_arr[:, i]
        y_pred_col = y_pred_binary[:, i]
        y_prob_col = y_pred_prob[:, i]

        precision = precision_score(y_true_col, y_pred_col, zero_division=0)
        recall    = recall_score(y_true_col, y_pred_col, zero_division=0)
        f1        = f1_score(y_true_col, y_pred_col, zero_division=0)
        accuracy = accuracy_score(y_true_col, y_pred_col)

        try:
            auc = roc_auc_score(y_true_col, y_prob_col)
        except ValueError:
            auc = float("nan")  # happens if only one class present in test set

        print(f"\n{label}")
        print(f"  Accuracy  : {accuracy:.4f}   ← misleading if imbalanced")
        print(f"  Precision : {precision:.4f}")
        print(f"  Recall    : {recall:.4f}   ← most important clinically")
        print(f"  F1 Score  : {f1:.4f}")
        print(f"  AUC-ROC   : {auc:.4f}")
        print(f"  Confusion Matrix:")
        cm = confusion_matrix(y_true_col, y_pred_col)
        print(f"    TN={cm[0,0]}  FP={cm[0,1]}")
        print(f"    FN={cm[1,0]}  TP={cm[1,1]}")

    print("\n" + "="*60)
    print("OVERALL CLASSIFICATION REPORT")
    print("="*60)
    print(classification_report(
        y_test_arr, y_pred_binary,
        target_names=label_columns,
        zero_division=0
    ))

    return y_pred_prob, y_pred_binary

def feature_importance_permutation(model, x_test_pad, y_test_arr,
                                   label_columns, feature_names, n_repeats=5):
    from sklearn.metrics import f1_score

    # baseline performance with all features intact
    y_pred_base = (model.predict(x_test_pad) >= 0.5).astype(int)
    baseline_f1 = f1_score(y_test_arr, y_pred_base, average="macro", zero_division=0)
    print(f"\nBaseline macro F1: {baseline_f1:.4f}")

    importances = {}

    for feat_idx, feat_name in enumerate(feature_names):
        scores = []
        for _ in range(n_repeats):
            # copy the test data
            x_permuted = x_test_pad.copy()
            # shuffle this feature across all reps and all timesteps
            np.random.shuffle(x_permuted[:, :, feat_idx])
            # predict with shuffled feature
            y_pred_perm = (model.predict(x_permuted, verbose=0) >= 0.5).astype(int)
            perm_f1 = f1_score(y_test_arr, y_pred_perm,
                               average="macro", zero_division=0)
            # importance = how much performance drops when this feature is shuffled
            scores.append(baseline_f1 - perm_f1)

        importances[feat_name] = np.mean(scores)

    # sort by importance descending
    importances_sorted = dict(
        sorted(importances.items(), key=lambda x: x[1], reverse=True)
    )

    print("\n" + "="*60)
    print("FEATURE IMPORTANCE (permutation)")
    print("higher = more important")
    print("="*60)
    for feat, imp in importances_sorted.items():
        bar = "█" * max(0, int(imp * 100))
        print(f"  {feat:<40} {imp:+.4f}  {bar}")

    return importances_sorted

"""MAIN PIPELINE

"""

def main_pipeline():
    # load
    x, y, metadata, metadata_labels, label_columns = load_dataset(CSV_PATH, LABEL_CSV)

    # split
    (x_train, x_test, x_val,
     y_train, y_test, y_val,
     metadata_train, metadata_test, metadata_val,
     metadata_labels_train, metadata_labels_test,
     metadata_labels_val) = split_dataset(x, y, metadata, metadata_labels)

    # encode phase label
    x_train, x_test, x_val, encoder = encode_features(x_train, x_test, x_val)

    # scale numerical features
    x_train, x_test, x_val = scale_features(x_train, x_test, x_val)

    # store feature names before converting to numpy
    feature_names = list(x_train.columns)

    # build sequences
    x_train_seq, train_keys = create_sequences(x_train, metadata_train)
    x_test_seq,  test_keys  = create_sequences(x_test,  metadata_test)
    x_val_seq,   val_keys   = create_sequences(x_val,   metadata_val)

    # match labels to sequences
    x_train_seq, y_train_seq = match_labels(x_train_seq, train_keys, metadata_labels_train, y_train)
    x_test_seq,  y_test_seq  = match_labels(x_test_seq,  test_keys,  metadata_labels_test,  y_test)
    x_val_seq,   y_val_seq   = match_labels(x_val_seq,   val_keys,   metadata_labels_val,   y_val)

    # class imbalance
    class_weights = handle_class_imbalance(y_train_seq, label_columns)

    # pad sequences
    x_train_pad, y_train_arr, _, max_len = pad_sequences_custom(x_train_seq, y_train_seq)
    x_test_pad,  y_test_arr,  _, _       = pad_sequences_custom(x_test_seq,  y_test_seq)
    x_val_pad,   y_val_arr,   _, _       = pad_sequences_custom(x_val_seq,   y_val_seq)

    # ensure test and val are padded to same max_len as train
    # if shorter, pad them
    def ensure_length(arr, target_len):
        current_len = arr.shape[1]
        if current_len < target_len:
            # Pad if current length is shorter
            pad_width = target_len - current_len
            arr = np.pad(arr, ((0,0), (0,pad_width), (0,0)))
        elif current_len > target_len:
            # Truncate if current length is longer
            arr = arr[:, :target_len, :]
        return arr

    x_test_pad = ensure_length(x_test_pad, max_len)
    x_val_pad  = ensure_length(x_val_pad,  max_len)

    num_features = x_train_pad.shape[2]
    num_labels   = y_train_arr.shape[1]

    # build model
    model = build_lstm_model(
        num_features=num_features,
        num_labels=num_labels,
        max_len=max_len,
        hidden_size=64,
        dropout_rate=0.3,
        num_layers=1
    )

    # weighted loss
    weighted_loss_fn = build_weighted_loss(class_weights, label_columns, y_train_arr)

    # train
    model, history = compile_and_train(
        model,
        x_train_pad, y_train_arr,
        x_val_pad,   y_val_arr,
        weighted_loss_fn,
        epochs=100,
        batch_size=32
    )

    # evaluate
    y_pred_prob, y_pred_binary = evaluate_model(
        model, x_test_pad, y_test_arr, label_columns
    )

    # feature importance
    importances = feature_importance_permutation(
        model, x_test_pad, y_test_arr,
        label_columns, feature_names,
        n_repeats=3
    )

    # save model and everything needed for inference
    model.save("lstm_model.keras")
    np.save("feature_names.npy", feature_names)
    np.save("label_columns.npy", label_columns)
    print("\nModel and metadata saved.")

    return model, history, importances

if __name__ == "__main__":
    model, history, importances = main_pipeline()